package com.ayushdebbarma.myaiagent;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import java.io.InputStream;
import org.json.JSONArray;
import org.json.JSONObject;

/** Lightweight ChatGPT-style launcher UI for Axtor. */
public class ChatGPTActivity extends Activity {
    private static final int AUDIO = 42;
    private static final int MODEL_PICKER = 77;
    private static final String PREF = "axtor_chat";
    private static final String HISTORY = "history";
    private LinearLayout messages; private ScrollView scroll; private TextView status; private EditText input;
    private final android.os.Handler uiHandler=new android.os.Handler(android.os.Looper.getMainLooper());
    private final Runnable statusTicker=()->{updateStatus();uiHandler.postDelayed(statusTicker,500);};
    private int dp(float v) { return (int)(v * getResources().getDisplayMetrics().density + .5f); }
    @Override public void onCreate(Bundle state) { super.onCreate(state); buildInterface(); restoreHistory(); startWhenPermitted(); }
    private TextView label(String value,float size){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(Color.rgb(235,235,235));t.setPadding(dp(4),dp(4),dp(4),dp(4));return t;}
    private Button button(String value){Button b=new Button(this);b.setText(value);b.setAllCaps(false);return b;}
    private void buildInterface(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(32,33,35));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(12),dp(6),dp(8),dp(4));LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView title=label("Axtor",21);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);TextView sub=label("Personal Android AI assistant",12);sub.setTextColor(Color.LTGRAY);brand.addView(title);brand.addView(sub);top.addView(brand,new LinearLayout.LayoutParams(0,dp(54),1));Button newChat=button("＋");newChat.setContentDescription("New chat");newChat.setOnClickListener(v->newChat());top.addView(newChat,new LinearLayout.LayoutParams(dp(52),dp(52)));Button menu=button("⋮");menu.setTextSize(22);menu.setContentDescription("Axtor menu");menu.setOnClickListener(v->showFeatureMenu());top.addView(menu,new LinearLayout.LayoutParams(dp(52),dp(52)));root.addView(top);status=label("● Starting…",12);status.setTextColor(Color.LTGRAY);status.setPadding(dp(16),0,dp(16),dp(7));root.addView(status);scroll=new ScrollView(this);scroll.setFillViewport(true);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(8),dp(12),dp(12));scroll.addView(messages);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout composer=new LinearLayout(this);composer.setGravity(Gravity.BOTTOM);composer.setPadding(dp(9),dp(7),dp(9),dp(9));input=new EditText(this);input.setHint("Message Axtor…");input.setTextColor(Color.WHITE);input.setHintTextColor(Color.GRAY);input.setMaxLines(5);input.setBackgroundColor(Color.rgb(48,49,52));input.setPadding(dp(14),dp(7),dp(10),dp(7));composer.addView(input,new LinearLayout.LayoutParams(0,dp(54),1));Button mic=button("🎙");mic.setTextSize(19);mic.setContentDescription("Start voice mode");mic.setOnClickListener(v->startWhenPermitted());composer.addView(mic,new LinearLayout.LayoutParams(dp(56),dp(54)));Button send=button("➤");send.setTextSize(19);send.setContentDescription("Send message");send.setOnClickListener(v->sendMessage());composer.addView(send,new LinearLayout.LayoutParams(dp(56),dp(54)));root.addView(composer);setContentView(root);
    }
    private void addBubble(String value,boolean user,boolean save){if(value==null||value.trim().isEmpty())return;TextView b=label(value,16);b.setTextColor(Color.WHITE);b.setPadding(dp(15),dp(11),dp(15),dp(11));b.setBackgroundColor(user?Color.rgb(16,163,127):Color.rgb(52,53,65));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(user?dp(44):dp(3),dp(6),user?dp(3):dp(44),dp(6));p.gravity=user?Gravity.END:Gravity.START;messages.addView(b,p);if(save)saveMessage(user,value);scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}
    private void sendMessage(){String q=input.getText().toString().trim();if(q.isEmpty())return;addBubble(q,true,true);input.setText("");String policy=AxtorCommandSecurityPolicy.authorizeVoice(this,q);if(!"OK".equals(policy)){addBubble("I can't execute that request because it is blocked by Axtor's safety policy.",false,true);return;}addBubble("Thinking…",false,false);AxtorAgent.handle(this,q,new AxtorAgent.Callback(){public void onReply(String r){runOnUiThread(()->replaceThinking(r));}public void onError(String e){runOnUiThread(()->replaceThinking("I couldn't complete that: "+(e==null?"unknown error":e)));}});}
    private void replaceThinking(String value){if(messages.getChildCount()>0){View last=messages.getChildAt(messages.getChildCount()-1);if(last instanceof TextView&&"Thinking…".contentEquals(((TextView)last).getText()))messages.removeView(last);}addBubble(value==null?"No response.":value,false,true);}
    private void saveMessage(boolean user,String text){try{JSONArray a=new JSONArray(getSharedPreferences(PREF,0).getString(HISTORY,"[]"));JSONObject o=new JSONObject();o.put("user",user);o.put("text",text);a.put(o);while(a.length()>80)a.remove(0);getSharedPreferences(PREF,0).edit().putString(HISTORY,a.toString()).apply();}catch(Exception ignored){}}
    private void restoreHistory(){try{JSONArray a=new JSONArray(getSharedPreferences(PREF,0).getString(HISTORY,"[]"));if(a.length()==0){addBubble("Hello! I'm Axtor. Type a request or speak directly—no wake phrase is required.",false,true);return;}for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);addBubble(o.optString("text",""),o.optBoolean("user"),false);}}catch(Exception e){addBubble("Hello! I'm Axtor. You can type or speak a command directly.",false,true);}}
    private void newChat(){messages.removeAllViews();getSharedPreferences(PREF,0).edit().putString(HISTORY,"[]").apply();addBubble("New chat started. How can I help?",false,true);}
    private void startWhenPermitted(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},AUDIO);return;}if(!VoiceServiceState.isRunning()){try{VoiceCommandManager.repair(this);}catch(Exception ignored){Toast.makeText(this,"Voice service could not start.",Toast.LENGTH_SHORT).show();}}}
    @Override public void onRequestPermissionsResult(int code,String[] p,int[] r){super.onRequestPermissionsResult(code,p,r);if(code==AUDIO){if(r.length>0&&r[0]==PackageManager.PERMISSION_GRANTED)startWhenPermitted();else Toast.makeText(this,"Microphone permission is needed for voice mode.",Toast.LENGTH_SHORT).show();}}
    private void showFeatureMenu(){String[] items={"AI & Models","Voice & Snaps","Device & Files","Diagnostics","Setup guide"};new AlertDialog.Builder(this).setTitle("Axtor").setItems(items,(d,w)->{if(w==0)showAiMenu();else if(w==1)showVoiceMenu();else if(w==2)showDeviceMenu();else if(w==3)showDiagnostics();else showGuide();}).show();}
    private void showAiMenu(){String[] items={"Import GGUF model","Choose active model","Configure online AI","Model status"};new AlertDialog.Builder(this).setTitle("AI & Models").setItems(items,(d,w)->{if(w==0)pickModel();else if(w==1)chooseModel();else if(w==2)startActivity(new Intent(this,OnlineAiSetupActivity.class));else modelStatus();}).show();}
    private void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/octet-stream");startActivityForResult(i,MODEL_PICKER);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=MODEL_PICKER||resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{if(Build.VERSION.SDK_INT>=19)getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);InputStream in=getContentResolver().openInputStream(uri);String name=uri.getLastPathSegment();if(name==null||name.isEmpty())name="model.gguf";java.io.File f=LlamaRuntime.copyModel(this,in,name);AppCore.addLocalModel(this,f.getName(),f.getAbsolutePath());Toast.makeText(this,"GGUF imported and selected: "+f.getName(),Toast.LENGTH_LONG).show();updateStatus();}catch(Exception e){Toast.makeText(this,"Model import failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void chooseModel(){try{JSONArray a=AppCore.models(this);if(a.length()==0){Toast.makeText(this,"No imported models yet.",Toast.LENGTH_SHORT).show();return;}String[] names=new String[a.length()];for(int i=0;i<a.length();i++)names[i]=a.getJSONObject(i).optString("name","Model "+(i+1));new AlertDialog.Builder(this).setTitle("Active GGUF model").setItems(names,(d,w)->{try{String p=a.getJSONObject(w).optString("path","");if(!p.isEmpty()){AppCore.setActiveModel(this,p);Toast.makeText(this,"Active model: "+names[w],Toast.LENGTH_SHORT).show();updateStatus();}}catch(Exception ignored){}}).show();}catch(Exception e){Toast.makeText(this,"Could not read model list.",Toast.LENGTH_SHORT).show();}}
    private void modelStatus(){String p=AppCore.activeModel(this);String text=p.isEmpty()?"No local model selected.":"Local model: "+p+"\nReadiness: "+LlamaRuntime.modelReadiness(this,p)+"\nLoaded: "+LlamaRuntime.isModelLoaded()+"\nOnline AI: "+(OnlineAiRouter.configured(this)?"configured":"not configured");new AlertDialog.Builder(this).setTitle("Model status").setMessage(text).setPositiveButton("OK",null).show();}
    private void showVoiceMenu(){String[] items={"Start voice service","Stop voice service","Enroll personal snaps","Enable snap commands","Disable snap commands","Toggle extended-range snaps","Snap settings","Voice diagnostics"};new AlertDialog.Builder(this).setTitle("Voice & Snaps").setMessage("Live: "+SnapTriggerEngine.liveStatus(this)+"\nEnrollment: "+SnapTriggerEngine.enrollmentProgress(this)+"/3").setItems(items,(d,w)->{switch(w){case 0:startWhenPermitted();break;case 1:stopService(new Intent(this,VoiceAssistantService.class));VoiceServiceState.setRunning(false);break;case 2:enrollSnaps();break;case 3:setSnap(true);break;case 4:setSnap(false);break;case 5:boolean n=!SnapTriggerEngine.isExtendedRangeEnabled(this);SnapTriggerEngine.setExtendedRangeEnabled(this,n);Toast.makeText(this,n?"Extended-range snaps ON":"Extended-range snaps OFF",Toast.LENGTH_SHORT).show();break;case 6:showSnapSettings();break;default:showDiagnostics();}}).show();}
    private void showSnapSettings(){String[] items={"Enable snap commands","Disable snap commands","Extended-range: "+(SnapTriggerEngine.isExtendedRangeEnabled(this)?"ON":"OFF"),"Re-enroll personal snaps","Clear snap enrollment"};new AlertDialog.Builder(this).setTitle("Snap settings").setMessage("Status: "+SnapTriggerEngine.liveStatus(this)+"\nEnrollment: "+SnapTriggerEngine.enrollmentProgress(this)+"/3").setItems(items,(d,w)->{if(w==0)setSnap(true);else if(w==1)setSnap(false);else if(w==2){boolean n=!SnapTriggerEngine.isExtendedRangeEnabled(this);SnapTriggerEngine.setExtendedRangeEnabled(this,n);showSnapSettings();}else if(w==3)enrollSnaps();else{new AlertDialog.Builder(this).setTitle("Clear snap enrollment?").setMessage("This removes the saved personal snap template. You can enroll again later.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(x,y)->{SnapTriggerEngine.clearEnrollment(this);Toast.makeText(this,"Snap enrollment cleared.",Toast.LENGTH_SHORT).show();updateStatus();}).show();}}).show();}
    private void enrollSnaps(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},AUDIO);Toast.makeText(this,"Microphone permission is needed before snap enrollment.",Toast.LENGTH_LONG).show();return;}final boolean wasRunning=VoiceServiceState.isRunning();getSharedPreferences("axtor_voice",0).edit().putBoolean("snap_command_patterns_enabled",false).apply();if(wasRunning){stopService(new Intent(this,VoiceAssistantService.class));VoiceServiceState.setRunning(false);}Toast.makeText(this,"Voice paused. Make 3 distinct snaps in your normal environment; background noise is okay.",Toast.LENGTH_LONG).show();new Thread(()->{boolean ok=false;try{Thread.sleep(900);ok=SnapTriggerEngine.enroll(this);Thread.sleep(300);}catch(InterruptedException ignored){Thread.currentThread().interrupt();}final boolean result=ok;runOnUiThread(()->{if(wasRunning){try{startWhenPermitted();}catch(Exception ignored){}}Toast.makeText(this,result?"Personal snap enrolled successfully. Voice resumed.":"Enrollment failed. Check Axtor → Diagnostics for the capture result.",Toast.LENGTH_LONG).show();updateStatus();});},"AxtorSnapEnrollment").start();}
    private void setSnap(boolean enabled){if(enabled&&!SnapTriggerEngine.isEnrolled(this)){Toast.makeText(this,"Enroll your personal snaps first.",Toast.LENGTH_SHORT).show();return;}getSharedPreferences("axtor_voice",0).edit().putBoolean("snap_command_patterns_enabled",enabled).apply();if(enabled)startWhenPermitted();Toast.makeText(this,enabled?"Snap commands enabled.":"Snap commands disabled.",Toast.LENGTH_SHORT).show();}
    private void showDeviceMenu(){String[] items={"Grant file access","File access status","Open Android accessibility settings","Open app settings"};new AlertDialog.Builder(this).setTitle("Device & Files").setItems(items,(d,w)->{if(w==0)startActivity(new Intent(this,FileAccessActivity.class));else if(w==1)Toast.makeText(this,FileAgentTools.hasGrantedTree(this)?"Axtor file workspace is granted.":"No file workspace is granted.",Toast.LENGTH_LONG).show();else if(w==2)startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));else{Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);i.setData(Uri.parse("package:"+getPackageName()));startActivity(i);}}).show();}
    private void showDiagnostics(){new AlertDialog.Builder(this).setTitle("Axtor diagnostics").setMessage(VoiceCommandManager.diagnose(this)+"\n\nSnap enrollment: "+SnapTriggerEngine.enrollmentDiagnostic(this)+"\nSnap status: "+SnapTriggerEngine.liveStatus(this)+"\nEnrollment progress: "+SnapTriggerEngine.enrollmentProgress(this)+"/3\nLocal model: "+(AppCore.hasUsableActiveModel(this)?"ready":"not ready")+"\nOnline AI: "+(OnlineAiRouter.configured(this)?"configured":"not configured")+"\nSnaps: "+(SnapTriggerEngine.isEnrolled(this)?"enrolled":"not enrolled")+"\nAccessibility: "+AxtorAgent.accessibilityStatus(this)).setPositiveButton("OK",null).show();}
    private void showGuide(){new AlertDialog.Builder(this).setTitle("Axtor quick guide").setMessage("CHAT — Type a request and press ➤. New chat clears local conversation history.\n\nVOICE — Tap 🎙 or Voice & Snaps → Start voice service. Speak the command directly; no wake phrase is required.\n\nSNAPS — Enroll 3 personal snaps, then enable snap commands. The top status automatically shows enrollment progress and the current snap counter. 1 snap = listen, 2 snaps = configured safe action, 3 snaps = emergency stop armed, 4 snaps = configured safe action.\n\nSNAP SETTINGS — Voice & Snaps → Snap settings lets you enable/disable snaps, toggle extended range, re-enroll, or clear the template.\n\nAI — AI & Models lets you import a GGUF model, select it, view readiness, or configure online AI.\n\nFILES — Device & Files → Grant file access gives the file agent a user-selected workspace.\n\nSAFETY — Axtor intentionally blocks root/shell/ADB, unlocking/bypass, destructive operations, credential access, and disabling Android protections.").setPositiveButton("OK",null).show();}
    private void updateStatus(){if(status==null)return;String mode=AppCore.hasUsableActiveModel(this)?"Local model ready":(OnlineAiRouter.configured(this)?"Online AI configured":"No AI model configured");String snap=SnapTriggerEngine.isEnrolled(this)?SnapTriggerEngine.liveStatus(this):"Snaps: not enrolled (0/3)";int progress=SnapTriggerEngine.enrollmentProgress(this);if(progress>0&&progress<3)snap="Snap enrollment: "+progress+"/3";status.setText((VoiceServiceState.isRunning()?"● Voice active":"○ Voice stopped")+"  •  "+mode+"\n"+snap);}
    @Override protected void onResume(){super.onResume();updateStatus();uiHandler.removeCallbacks(statusTicker);uiHandler.post(statusTicker);}
    @Override protected void onPause(){uiHandler.removeCallbacks(statusTicker);super.onPause();}
}
