package com.ayushdebbarma.myaiagent;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.view.Gravity;import android.widget.*;

/** Snap settings with selectable detector protocol and live diagnostics. */
public class SoundTriggerActivity extends Activity{
 LinearLayout content; Handler handler=new Handler(Looper.getMainLooper()); boolean diagnosticsTab=false;
 TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.rgb(32,33,35));t.setPadding(16,10,16,10);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);build();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",32);back.setOnClickListener(v->finish());h.addView(back,new LinearLayout.LayoutParams(48,58));TextView title=tv("Snap trigger settings",20);title.setTypeface(null,1);h.addView(title);root.addView(h);LinearLayout tabs=new LinearLayout(this);Button s=btn("Setup"),d=btn("Diagnostics");tabs.addView(s,new LinearLayout.LayoutParams(0,-2,1));tabs.addView(d,new LinearLayout.LayoutParams(0,-2,1));root.addView(tabs);s.setOnClickListener(v->{diagnosticsTab=false;render();});d.setOnClickListener(v->{diagnosticsTab=true;render();});ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(12,12,12,24);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render();}
 void render(){content.removeAllViews();if(diagnosticsTab)renderDiagnostics();else renderSetup();}
 void renderSetup(){
  String mode=SnapDetectionProtocol.get(this);content.addView(tv("Detection protocol",27));content.addView(tv("Current: "+SnapDetectionProtocol.label(this),15));
  RadioGroup g=new RadioGroup(this);RadioButton a=new RadioButton(this),r=new RadioButton(this),l=new RadioButton(this);a.setId(1001);r.setId(1002);l.setId(1003);a.setText("Adaptive personal detector\nLearns your acoustic snap profile.");r.setText("Band-pass transient detector (recommended test)\n1.5–3.5 kHz + 256-sample frames / 50% overlap + energy-rise detection.");l.setText("Classic / old detector\nKeeps the previous RMS/peak/ZCR detector.");g.addView(a);g.addView(r);g.addView(l);g.check(SnapDetectionProtocol.RESEARCH.equals(mode)?1002:SnapDetectionProtocol.LEGACY.equals(mode)?1003:1001);g.setOnCheckedChangeListener((x,id)->{String m=id==1002?SnapDetectionProtocol.RESEARCH:id==1003?SnapDetectionProtocol.LEGACY:SnapDetectionProtocol.ADAPTIVE;SnapDetectionProtocol.set(this,m);stopAll();render();});content.addView(g);
  if(SnapDetectionProtocol.ADAPTIVE.equals(mode)){boolean enrolled=SnapTriggerEngine.isEnrolled(this);content.addView(tv(enrolled?"✓ Adaptive profile enrolled":"No adaptive profile enrolled",15));Button e=btn(enrolled?"Re-learn personal snap":"Enroll 3 personal snaps");e.setOnClickListener(v->enroll());content.addView(e);Button clear=btn("Clear personal snap");clear.setOnClickListener(v->{SnapTriggerEngine.clearEnrollment(this);render();});content.addView(clear);}
  content.addView(tv("Research protocol: published finger-snap transient work uses a 1.5–3.5 kHz band-pass, 256-sample frames with 50% overlap, and abrupt short-time-energy rise detection. Axtor adapts that approach to 16 kHz Android capture.",13));
  Button start=btn("Enable selected snap detector");start.setOnClickListener(v->startSelected());content.addView(start);Button stop=btn("Stop snap detector");stop.setOnClickListener(v->{stopAll();Toast.makeText(this,"Snap detector stopped.",Toast.LENGTH_SHORT).show();});content.addView(stop);
 }
 void renderDiagnostics(){content.addView(tv("Snap diagnostics",27));TextView live=tv("",13);content.addView(live);Button setup=btn("Back to setup");setup.setOnClickListener(v->{diagnosticsTab=false;render();});content.addView(setup);Runnable q=new Runnable(){public void run(){if(!diagnosticsTab)return;live.setText("Protocol: "+SnapDetectionProtocol.label(SoundTriggerActivity.this)+"\n\n"+SnapTriggerEngine.diagnosticsSummary(SoundTriggerActivity.this));handler.postDelayed(this,500);}};handler.post(q);}
 void enroll(){if(!SnapDetectionProtocol.ADAPTIVE.equals(SnapDetectionProtocol.get(this)))return;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);return;}stopAll();Toast.makeText(this,"Stay quiet for calibration, then make 3 distinct snaps.",Toast.LENGTH_LONG).show();new Thread(()->{boolean ok=SnapTriggerEngine.enroll(this);runOnUiThread(()->Toast.makeText(this,ok?"Adaptive snap enrolled.":"Enrollment failed; open Diagnostics.",Toast.LENGTH_LONG).show());},"AxtorSnapEnrollment").start();}
 void startSelected(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);return;}String m=SnapDetectionProtocol.get(this);stopAll();if(SnapDetectionProtocol.ADAPTIVE.equals(m)){if(!SnapTriggerEngine.isEnrolled(this)){Toast.makeText(this,"Enroll your personal snap first.",Toast.LENGTH_SHORT).show();return;}getSharedPreferences("axtor_voice",0).edit().putBoolean("snap_trigger_enabled",true).putBoolean("snap_command_patterns_enabled",true).putBoolean("continuous_listening",true).apply();startServiceCompat(new Intent(this,VoiceAssistantService.class));}else{getSharedPreferences("axtor_voice",0).edit().putBoolean("snap_trigger_enabled",false).putBoolean("snap_command_patterns_enabled",false).putBoolean("continuous_listening",false).apply();startServiceCompat(new Intent(this,SoundTriggerService.class));}Toast.makeText(this,"Enabled: "+SnapDetectionProtocol.label(this),Toast.LENGTH_SHORT).show();}
 void startServiceCompat(Intent i){try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception e){Toast.makeText(this,"Android blocked microphone service: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void stopAll(){try{stopService(new Intent(this,VoiceAssistantService.class));}catch(Exception ignored){}try{stopService(new Intent(this,SoundTriggerService.class));}catch(Exception ignored){}getSharedPreferences("axtor_voice",0).edit().putBoolean("snap_command_patterns_enabled",false).apply();}
 @Override protected void onResume(){super.onResume();if(content!=null)render();}
 @Override protected void onPause(){super.onPause();handler.removeCallbacksAndMessages(null);}
}
