package com.ayushdebbarma.myaiagent;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.view.Gravity;import android.widget.*;
/** ChatGPT-inspired compact settings surface for personalized snap wake mode. */
public class SoundTriggerActivity extends Activity{
 LinearLayout content;TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.rgb(32,33,35));t.setPadding(16,10,16,10);return t;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);build();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);LinearLayout header=new LinearLayout(this);header.setPadding(10,8,10,8);header.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",32);back.setOnClickListener(v->finish());header.addView(back,new LinearLayout.LayoutParams(48,58));TextView title=tv("Snap trigger",20);title.setTypeface(null,1);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));root.addView(header);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(12,12,12,24);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render();}
 void render(){content.removeAllViews();android.content.SharedPreferences p=getSharedPreferences("axtor_voice",0);boolean enabled=p.getBoolean("snap_trigger_enabled",true),enrolled=SnapTriggerEngine.isEnrolled(this),extended=SnapTriggerEngine.isExtendedRangeEnabled(this);content.addView(tv("Personal snap",28));content.addView(tv(enrolled?"✓ Your snap pattern is enrolled on this device":"Set up your personal snap to use hands-free wake",15));
 Switch sw=new Switch(this);sw.setText("Require my enrolled snap");sw.setTextSize(16);sw.setChecked(enabled);sw.setOnCheckedChangeListener((v,on)->{p.edit().putBoolean("snap_trigger_enabled",on).apply();if(on)startVoice();});content.addView(sw);
 Switch range=new Switch(this);range.setText("Extended-range snap detection");range.setTextSize(16);range.setChecked(extended);range.setOnCheckedChangeListener((v,on)->{SnapTriggerEngine.setExtendedRangeEnabled(this,on);});content.addView(range);content.addView(tv("Extended range lowers the acoustic trigger floor so a clear enrolled snap can be detected farther away. Actual distance depends on your phone microphone, walls, doors and ambient noise; it cannot guarantee an outdoor-to-indoor range.",13));
 Button enroll=btn(enrolled?"↻ Re-learn my snap":"Learn my snap");enroll.setOnClickListener(v->enroll());content.addView(enroll);Button clear=btn("Forget enrolled snap");clear.setOnClickListener(v->{SnapTriggerEngine.clearEnrollment(this);Toast.makeText(this,"Personal snap forgotten.",Toast.LENGTH_SHORT).show();render();});content.addView(clear);Button start=btn("Start hands-free mode");start.setOnClickListener(v->startVoice());content.addView(start);Button stop=btn("Stop hands-free mode");stop.setOnClickListener(v->{p.edit().putBoolean("continuous_listening",false).apply();stopService(new Intent(this,VoiceAssistantService.class));Toast.makeText(this,"Hands-free mode stopped.",Toast.LENGTH_SHORT).show();});content.addView(stop);
 content.addView(tv("How it works\n• Your phone listens locally for short snap-like transients.\n• A matching enrolled acoustic fingerprint is required before a command is accepted.\n• After one snap starts voice interaction, the emergency triple-snap watcher stays armed.\n• Three matching snaps within about 2.2 seconds request an immediate emergency stop.",14));content.addView(tv("Privacy & security\nNo snap recordings are uploaded. A compact acoustic feature template is stored locally. This is personalization, not a cryptographic biometric, so extended range should be used with awareness of false-trigger risk.",13));Button back=btn("Back to chat");back.setOnClickListener(v->finish());content.addView(back);}
 void enroll(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);return;}stopService(new Intent(this,VoiceAssistantService.class));Toast.makeText(this,"Snap 3 times normally. Enrollment may take a few seconds.",Toast.LENGTH_LONG).show();new Thread(()->{boolean ok=SnapTriggerEngine.enroll(this);runOnUiThread(()->{Toast.makeText(this,ok?"Snap pattern saved on this device.":"Could not capture 3 clear snaps. Try again.",Toast.LENGTH_LONG).show();render();});},"AxtorManualSnapEnrollment").start();}
 void startVoice(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);return;}p().edit().putBoolean("continuous_listening",true).putBoolean("snap_trigger_enabled",true).apply();Intent i=new Intent(this,VoiceAssistantService.class);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);Toast.makeText(this,SnapTriggerEngine.isEnrolled(this)?"Hands-free snap mode started.":"Voice started; follow the enrollment prompt.",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Android blocked the microphone service: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 android.content.SharedPreferences p(){return getSharedPreferences("axtor_voice",0);}@Override protected void onResume(){super.onResume();if(content!=null)render();}
}
