package com.ayushdebbarma.myaiagent;

import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.media.AudioManager;import android.os.*;import android.speech.*;import android.speech.tts.TextToSpeech;import java.util.*;

public class VoiceAssistantService extends Service implements RecognitionListener, TextToSpeech.OnInitListener {
  static final int ID=71; SpeechRecognizer recognizer; Intent recognizerIntent; TextToSpeech tts; boolean running=true;
  final String[] wakeWords={"hey myai","hey my ai","myai","my ai"};
  @Override public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("voice","MyAiAgent Voice",NotificationManager.IMPORTANCE_LOW);nm.createNotificationChannel(c);}Intent stop=new Intent(this,VoiceAssistantService.class);stop.setAction("STOP");PendingIntent pi=PendingIntent.getService(this,1,stop,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"voice"):new Notification.Builder(this);b.setContentTitle("MyAiAgent voice assistant").setContentText("Offline voice assistant active").setSmallIcon(android.R.drawable.ic_btn_speak_now).setOngoing(true).addAction(new Notification.Action.Builder(null,"Stop",pi).build());startForeground(ID,b.build());tts=new TextToSpeech(this,this);startRecognition();}
  void startRecognition(){if(!running||checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED)return;if(!SpeechRecognizer.isRecognitionAvailable(this))return;if(recognizer!=null)recognizer.destroy();recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(this);recognizerIntent=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);recognizerIntent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);recognizerIntent.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,false);recognizerIntent.putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,true);recognizerIntent.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,3);recognizer.startListening(recognizerIntent);}
  String extractCommand(String q){String l=q.toLowerCase(Locale.ROOT).trim();for(String w:wakeWords){int i=l.indexOf(w);if(i>=0)return q.substring(i+w.length()).trim();}return null;}
  void command(String q){String cmd=extractCommand(q);if(cmd==null||cmd.isEmpty())return;String l=cmd.toLowerCase(Locale.ROOT);try{if(l.contains("volume up")||l.contains("increase volume")){((AudioManager)getSystemService(AUDIO_SERVICE)).adjustVolume(AudioManager.ADJUST_RAISE,AudioManager.FLAG_PLAY_SOUND);say("Volume increased.");return;}if(l.contains("volume down")||l.contains("decrease volume")){((AudioManager)getSystemService(AUDIO_SERVICE)).adjustVolume(AudioManager.ADJUST_LOWER,AudioManager.FLAG_PLAY_SOUND);say("Volume decreased.");return;}String path=AppCore.activeModel(this);if(path.isEmpty()){say(AppCore.answer(cmd));return;}say("Thinking locally.");LlamaRuntime.generate(this,path,cmd,"You are MyAiAgent, a private offline Android voice assistant created by Ayush Debbarma. Answer briefly. Do not claim internet access.",192,new LlamaRuntime.Callback(){public void onSuccess(String text,double tps){say(text);}public void onError(String m){say("Local model error: "+m);}});}catch(Exception e){say("I couldn't perform that action: "+e.getMessage());}}
  void say(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"myai");}
  public int onStartCommand(Intent i,int f,int s){if(i!=null&&"STOP".equals(i.getAction())){stopSelf();return START_NOT_STICKY;}running=true;if(recognizer==null)startRecognition();return START_STICKY;}
  public void onDestroy(){running=false;if(recognizer!=null)recognizer.destroy();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
  public android.os.IBinder onBind(Intent i){return null;}
  public void onInit(int status){}
  public void onResults(Bundle r){ArrayList<String> x=r.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null)for(String candidate:x){String cmd=extractCommand(candidate);if(cmd!=null&&!cmd.isEmpty()){command(candidate);break;}}new Handler(Looper.getMainLooper()).postDelayed(()->startRecognition(),700);}
  public void onError(int e){new Handler(Looper.getMainLooper()).postDelayed(()->startRecognition(),1200);} public void onReadyForSpeech(Bundle b){} public void onBeginningOfSpeech(){} public void onRmsChanged(float v){} public void onBufferReceived(byte[] b){} public void onEndOfSpeech(){} public void onPartialResults(Bundle b){} public void onEvent(int a,Bundle b){}
}
